### ISSUE TITLE
Rename groups in exported cells

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#2]
Group names generated during export from NEURON should be renamed to standard ones (soma_group, dendrite_group, axon_group), e.g. ModelViewParmSubset_4 -> dendrite_group in https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NeuroML2/Mitral_0_0.cell.nml

Can infer correct group from names of included, e.g. all XdenX  => dendrite_group, hillock + initialseg => axon_group etc.

Can use libNeuroML during reload/write here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NeuroML2/export_mitral.py

**Comment by JustasB** [comment]
Couple of questions @pgleeson:
1) What's the general goal here? You need an NML file that contains the standard groups, so it works with the rest of neuroml libraries? And is the current problem here because the mitral.hoc file does not have the groups, but the existing segments can be heuristically assigned to one of the standard groups?

2) There are 4 groups in the generated NML, but only 3 standard ones (soma_group, dendrite_group, axon_group). What do you want to do with the extra group?

These are the groups present in the NML:
ModelViewParmSubset_1
ModelViewParmSubset_2
ModelViewParmSubset_3
ModelViewParmSubset_4

3) Do you suggest (1) changing the group names AFTER the NML is generated with export_to_neuroml2 function, OR (2) the export_to_neuroml2 function should be modified so it generates the NML with the standard group names?

**Comment by JustasB** [comment]
I didn't hear back in time. I'm handling the ModelViewP... groups by removing them and then replacing them with the standard all, axon, soma, and dendrite groups. See the bottom of the cell files in the above pull request.

**Comment by pgleeson** [comment]
Since the info on conductances, capacitance etc. will all be added afterwards, then yes, all of the Neuron generated groups can be removed, and the only ones needed are the "standard" ones used in NML1/2. Changing the nml file after generation in export_mitral.py was the right way to go.

Looks like this has been done correctly in the PR, though you seem to have used an older version of pyNeuroML. I'll merge and update, but you should update this (and libNeuroML) locally.

**Comment by JustasB** [comment]
> > seem to have used an older version of pyNeuroML<<

Ah, maybe this explains the weird path issues I was seeing. Will update.

**Comment by pgleeson** [comment]
This is an example of how the standard group names are useful:

![selection_009](https://cloud.githubusercontent.com/assets/1556687/11749185/2fc36b0a-a024-11e5-891e-9c8fdebf341b.png)

**Comment by JustasB** [comment]
Oh I see, very nice

**Comment by JustasB** [comment]
Old local version of pyNeuroML was it. I've removed the workaround in this pr: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/9
